name: Build latest GCC
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - uses: actions/checkout@v4

      - name: Setup build prerequisites
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential file flex texinfo wget xz-utils zstd

      - name: Build GCC
        uses: libbpf/ci/build-bpf-gcc@main
        with:
          install-dir: gcc-bpf

      - name: Update release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: ./update-latest-release.sh gcc-bpf

